// Code generated by scratchpad/advgen from Open Adventure's adventure.yaml.
// DO NOT EDIT. Regenerate with: go run . <adventure.yaml> storydata_gen.go
//
// Source: Colossal Cave Adventure by Will Crowther & Don Woods, via Open
// Adventure (Eric S. Raymond), gitlab.com/esr/open-adventure, BSD-2-Clause.
// Phase-1 subset: surface world + first cave (see SPEC_TEXT_ADVENTURE.md §2).

package story

// Location ids (index into Locations).
const (
	LOC_NOWHERE     LocID = 0
	LOC_START       LocID = 1
	LOC_HILL        LocID = 2
	LOC_BUILDING    LocID = 3
	LOC_VALLEY      LocID = 4
	LOC_ROADEND     LocID = 5
	LOC_SLIT        LocID = 6
	LOC_GRATE       LocID = 7
	LOC_BELOWGRATE  LocID = 8
	LOC_COBBLE      LocID = 9
	LOC_DEBRIS      LocID = 10
	LOC_AWKWARD     LocID = 11
	LOC_BIRDCHAMBER LocID = 12
	LOC_PITTOP      LocID = 13
	LOC_MISTHALL    LocID = 14
	LOC_NUGGET      LocID = 15
)

// Object ids (index into Objects).
const (
	OBJ_NONE   ObjID = 0
	OBJ_KEYS   ObjID = 1
	OBJ_LAMP   ObjID = 2
	OBJ_GRATE  ObjID = 3
	OBJ_CAGE   ObjID = 4
	OBJ_ROD    ObjID = 5
	OBJ_BIRD   ObjID = 6
	OBJ_FOOD   ObjID = 7
	OBJ_BOTTLE ObjID = 8
	OBJ_NUGGET ObjID = 9
)

// Object state indices.
const (
	LAMP_DARK    = 0
	LAMP_BRIGHT  = 1
	GRATE_CLOSED = 0
	GRATE_OPEN   = 1
	BIRD_UNCAGED = 0
	BIRD_CAGED   = 1
)

// Magic-word motions.
const (
	MotXYZZY Motion = 62
	MotPLUGH Motion = 65
)

var Locations = []Location{
	{ // LOC_NOWHERE
		Long:  ``,
		Short: `Nowhere`,
		Lit:   false, Forest: false, Deep: false,
	},
	{ // LOC_START
		Long:  `You are standing at the end of a road before a small brick building. Around you is a forest. A small stream flows out of the building and down a gully.`,
		Short: `You're in front of building.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{2, 44, 29}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 2, Msg: 0},
			{Verbs: []Motion{3, 12, 19, 43}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 3, Msg: 0},
			{Verbs: []Motion{5, 13, 14, 46, 30}, Dir: 46, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 4, Msg: 0},
			{Verbs: []Motion{6, 45}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{63}, Dir: 63, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
		},
	},
	{ // LOC_HILL
		Long:  `You have walked up a hill, still in the forest. The road slopes back down the other side of the hill. There is a building in the distance.`,
		Short: `You're at hill in road.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{12, 43}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 1, Msg: 0},
			{Verbs: []Motion{44}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 5, Msg: 0},
			{Verbs: []Motion{45}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{46, 6}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{30}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 1},
		},
	},
	{ // LOC_BUILDING
		Long:  `You are inside a building, a well house for a large spring.`,
		Short: `You're inside building.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{11, 32, 44}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 1, Msg: 0},
			{Verbs: []Motion{62}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{65}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{5, 14}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
		},
	},
	{ // LOC_VALLEY
		Long:  `You are in a valley in the forest beside a stream tumbling along a rocky bed.`,
		Short: `You're in valley.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{4, 12, 45}, Dir: 45, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 1, Msg: 0},
			{Verbs: []Motion{43, 6}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{44}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{5, 46, 30}, Dir: 46, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 6, Msg: 0},
			{Verbs: []Motion{63}, Dir: 63, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
			{Verbs: []Motion{14}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 2},
		},
	},
	{ // LOC_ROADEND
		Long:  `The road, which approaches from the east, ends here amid the trees.`,
		Short: `You're at end of road.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{2, 43, 29}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 2, Msg: 0},
			{Verbs: []Motion{12}, Dir: 12, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 1, Msg: 0},
			{Verbs: []Motion{46, 6}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{44}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{45}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
		},
	},
	{ // LOC_SLIT
		Long:  `At your feet all the water of the stream splashes into a 2-inch slit in the rock. Downstream the streambed is bare rock.`,
		Short: `You're at slit in streambed.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{12}, Dir: 12, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 1, Msg: 0},
			{Verbs: []Motion{4, 45}, Dir: 45, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 4, Msg: 0},
			{Verbs: []Motion{43, 6}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{44}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{5, 16, 46, 63}, Dir: 46, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
			{Verbs: []Motion{60, 14, 30, 19, 3}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 3},
		},
	},
	{ // LOC_GRATE
		Long:  `You are in a 20-foot depression floored with bare dirt. Set into the dirt is a strong steel grate mounted in concrete. A dry streambed leads into the depression.`,
		Short: `You're outside grate.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{43, 6}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{46}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{44}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{12}, Dir: 12, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 1, Msg: 0},
			{Verbs: []Motion{4, 13, 45}, Dir: 45, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 6, Msg: 0},
			{Verbs: []Motion{3, 19, 30}, Dir: 30, Cond: Cond{Kind: CondNotState, Obj: 3, State: 0, Pct: 0}, Act: ActGoto, Dest: 8, Msg: 0},
			{Verbs: []Motion{3}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 4},
		},
	},
	{ // LOC_BELOWGRATE
		Long:  `You are in a small chamber beneath a 3x3 steel grate to the surface. A low crawl over cobbles leads inward to the west.`,
		Short: `You're below the grate.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{11, 29}, Dir: 29, Cond: Cond{Kind: CondNotState, Obj: 3, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
			{Verbs: []Motion{11}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 4},
			{Verbs: []Motion{17, 18, 19, 44}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 9, Msg: 0},
			{Verbs: []Motion{31}, Dir: 31, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 13, Msg: 0},
			{Verbs: []Motion{51}, Dir: 51, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 10, Msg: 0},
		},
	},
	{ // LOC_COBBLE
		Long:  `You are crawling over cobbles in a low passage. There is a dim light at the east end of the passage.`,
		Short: `You're in cobble crawl.`,
		Lit:   true, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{11, 20, 43}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 8, Msg: 0},
			{Verbs: []Motion{19, 22, 44, 51}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 10, Msg: 0},
			{Verbs: []Motion{31}, Dir: 31, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 13, Msg: 0},
		},
	},
	{ // LOC_DEBRIS
		Long:  `You are in a debris room filled with stuff washed in from the surface. A low wide passage with cobbles becomes plugged with mud and debris here, but an awkward canyon leads upward and west. In the mud someone has scrawled, "MAGIC WORD XYZZY".`,
		Short: `You're in debris room.`,
		Lit:   false, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{63}, Dir: 63, Cond: Cond{Kind: CondNotState, Obj: 3, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
			{Verbs: []Motion{64}, Dir: 64, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 8, Msg: 0},
			{Verbs: []Motion{17, 18, 23, 24, 43}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 9, Msg: 0},
			{Verbs: []Motion{25, 19, 29, 44}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 11, Msg: 0},
			{Verbs: []Motion{62}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{31}, Dir: 31, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 13, Msg: 0},
		},
	},
	{ // LOC_AWKWARD
		Long:  `You are in an awkward sloping east/west canyon.`,
		Short: `Awkward canyon.`,
		Lit:   false, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{63}, Dir: 63, Cond: Cond{Kind: CondNotState, Obj: 3, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
			{Verbs: []Motion{64}, Dir: 64, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 8, Msg: 0},
			{Verbs: []Motion{30, 43, 51}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 10, Msg: 0},
			{Verbs: []Motion{19, 29, 44}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 12, Msg: 0},
			{Verbs: []Motion{31}, Dir: 31, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 13, Msg: 0},
		},
	},
	{ // LOC_BIRDCHAMBER
		Long:  `You are in a splendid chamber thirty feet high. The walls are frozen rivers of orange stone. An awkward canyon and a good passage exit from east and west sides of the chamber.`,
		Short: `You're in bird chamber.`,
		Lit:   false, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{63}, Dir: 63, Cond: Cond{Kind: CondNotState, Obj: 3, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
			{Verbs: []Motion{64}, Dir: 64, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 8, Msg: 0},
			{Verbs: []Motion{51}, Dir: 51, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 10, Msg: 0},
			{Verbs: []Motion{25, 43}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 11, Msg: 0},
			{Verbs: []Motion{23, 31, 44}, Dir: 44, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 13, Msg: 0},
		},
	},
	{ // LOC_PITTOP
		Long:  `At your feet is a small pit breathing traces of white mist. An east passage ends here except for a small crack leading on.`,
		Short: `You're at top of small pit.`,
		Lit:   false, Forest: false, Deep: false,
		Travel: []Travel{
			{Verbs: []Motion{63}, Dir: 63, Cond: Cond{Kind: CondNotState, Obj: 3, State: 0, Pct: 0}, Act: ActGoto, Dest: 7, Msg: 0},
			{Verbs: []Motion{64}, Dir: 64, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 8, Msg: 0},
			{Verbs: []Motion{51}, Dir: 51, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 10, Msg: 0},
			{Verbs: []Motion{23, 43}, Dir: 43, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 12, Msg: 0},
			{Verbs: []Motion{30, 31, 34}, Dir: 0, Cond: Cond{Kind: CondCarry, Obj: 9, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{30}, Dir: 30, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 14, Msg: 0},
			{Verbs: []Motion{33, 44}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
		},
	},
	{ // LOC_MISTHALL
		Long:  `You are at one end of a vast hall stretching forward out of sight to the west. There are openings to either side. Nearby, a wide stone staircase leads downward. The hall is filled with wisps of white mist swaying to and fro almost as if alive. A cold wind blows up the staircase. There is a passage at the top of a dome behind you.`,
		Short: `You're in Hall of Mists.`,
		Lit:   false, Forest: false, Deep: true,
		Travel: []Travel{
			{Verbs: []Motion{36, 46}, Dir: 46, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 15, Msg: 0},
			{Verbs: []Motion{7, 38, 44}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{10, 30, 45}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{29, 31, 34, 35, 23, 43}, Dir: 0, Cond: Cond{Kind: CondCarry, Obj: 9, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
			{Verbs: []Motion{29}, Dir: 29, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 13, Msg: 0},
			{Verbs: []Motion{55}, Dir: 0, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActMessage, Dest: 0, Msg: 0},
		},
	},
	{ // LOC_NUGGET
		Long:  `This is a low room with a crude note on the wall. The note says, "You won't get it up the steps".`,
		Short: `You're in nugget-of-gold room.`,
		Lit:   false, Forest: false, Deep: true,
		Travel: []Travel{
			{Verbs: []Motion{38, 11, 45}, Dir: 45, Cond: Cond{Kind: CondNone, Obj: 0, State: 0, Pct: 0}, Act: ActGoto, Dest: 14, Msg: 0},
		},
	},
}

var Objects = []Object{
	{ // NO_OBJECT
		Words:     nil,
		Inventory: ``,
		Start:     0, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // KEYS
		Words:        []string{`keys`, `key`},
		Inventory:    `Set of keys`,
		Descriptions: []string{`There are some keys on the ground here.`},
		Start:        3, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // LAMP
		Words:        []string{`lamp`, `lante`},
		Inventory:    `Brass lantern`,
		States:       []string{`LAMP_DARK`, `LAMP_BRIGHT`},
		Descriptions: []string{`There is a shiny brass lamp nearby.`, `There is a lamp shining nearby.`},
		Start:        3, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // GRATE
		Words:        []string{`grate`},
		Inventory:    `*grate`,
		States:       []string{`GRATE_CLOSED`, `GRATE_OPEN`},
		Descriptions: []string{`The grate is locked.`, `The grate is open.`},
		Start:        7, Start2: 8, Immovable: true, Treasure: false,
	},
	{ // CAGE
		Words:        []string{`cage`},
		Inventory:    `Wicker cage`,
		Descriptions: []string{`There is a small wicker cage discarded nearby.`},
		Start:        9, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // ROD
		Words:        []string{`rod`},
		Inventory:    `Black rod`,
		Descriptions: []string{`A three foot black rod with a rusty star on an end lies nearby.`},
		Start:        10, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // BIRD
		Words:        []string{`bird`},
		Inventory:    `Little bird in cage`,
		States:       []string{`BIRD_UNCAGED`, `BIRD_CAGED`, `BIRD_FOREST_UNCAGED`},
		Descriptions: []string{`A cheerful little bird is sitting here singing.`, `There is a little bird in the cage.`, `A cheerful little bird is sitting here singing.`},
		Start:        12, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // FOOD
		Words:        []string{`food`, `ratio`},
		Inventory:    `Tasty food`,
		Descriptions: []string{`There is food here.`},
		Start:        3, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // BOTTLE
		Words:        []string{`bottl`, `jar`},
		Inventory:    `Small bottle`,
		States:       []string{`WATER_BOTTLE`, `EMPTY_BOTTLE`, `OIL_BOTTLE`},
		Descriptions: []string{`There is a bottle of water here.`, `There is an empty bottle here.`, `There is a bottle of oil here.`},
		Start:        3, Start2: 0, Immovable: false, Treasure: false,
	},
	{ // NUGGET
		Words:        []string{`gold`, `nugge`},
		Inventory:    `Large gold nugget`,
		Descriptions: []string{`There is a large sparkling nugget of gold here!`},
		Start:        15, Start2: 0, Immovable: false, Treasure: true,
	},
}

var Messages = []string{
	`You can't go that way — the passage leads deeper than this chapter of the cave.`,
	`Which way?`,
	`Upstream or downstream?`,
	`You don't fit through a two-inch slit!`,
	`You can't go through a locked steel grate!`,
}

// MotionSwedish maps a Motion id to its exit-button label.
var MotionSwedish = map[Motion]string{
	2:  `Vägen`,         // road
	3:  `Gå in`,         // enter
	4:  `Uppströms`,     // upstr
	5:  `Nedströms`,     // downs
	6:  `Skogen`,        // fores
	7:  `Framåt`,        // forwa
	10: `Trappan`,       // stair
	11: `Ut`,            // out
	12: `Byggnaden`,     // build
	13: `Ravinen`,       // gully
	14: `Bäcken`,        // strea
	16: `Bädden`,        // bed
	17: `Krypa`,         // crawl
	18: `Kullerstenar`,  // cobbl
	19: `In`,            // inwar
	20: `Ytan`,          // surfa
	22: `Mörkret`,       // dark
	23: `Gången`,        // passa
	24: `Låg gång`,      // low
	25: `Kanjonen`,      // canyo
	29: `Upp`,           // upwar
	30: `Ner`,           // d
	31: `Gropen`,        // pit
	32: `Outdo`,         // outdo
	33: `Sprickan`,      // crack
	34: `Stegen`,        // steps
	35: `Kupolen`,       // dome
	36: `Vänster`,       // left
	38: `Hallen`,        // hall
	43: `Öster`,         // east
	44: `Väster`,        // west
	45: `Norr`,          // north
	46: `Söder`,         // south
	51: `Bråtet`,        // debri
	55: `Y2`,            // y2
	60: `Springan`,      // slit
	62: `Xyzzy`,         // xyzzy
	63: `Fördjupningen`, // depre
	64: `Ingången`,      // entra
	65: `Plugh`,         // plugh
}

// MagicWords are the discoverable spoken words offered in the Säg… menu.
var MagicWords = []Motion{MotXYZZY}

// MagicWordText is the display label for each magic word.
var MagicWordText = map[Motion]string{MotXYZZY: "Xyzzy"}
